[servers.sample]
bind = "0.0.0.0:80"
protocol = "tcp"
balance = "weight"

max_connections = 10000
client_idle_timeout = "10m"
backend_idle_timeout = "10m"
backend_connection_timeout = "2s"

[servers.sample.discovery]
kind = "static"

static_list =[
 "ec2-54-183-215-25.us-west-1.compute.amazonaws.com:8080 weight=5",
 "ec2-54-183-215-25.us-west-1.compute.amazonaws.com:8081 weight=5",
 "ec2-54-183-215-25.us-west-1.compute.amazonaws.com:8082 weight=5",
 "ec2-54-183-215-25.us-west-1.compute.amazonaws.com:8083 weight=5", 
 "ec2-54-67-8-219.us-west-1.compute.amazonaws.com:8080 weight=5",
 "ec2-54-67-8-219.us-west-1.compute.amazonaws.com:8081 weight=5",
 "ec2-54-67-8-219.us-west-1.compute.amazonaws.com:8082 weight=5",
 "ec2-54-67-8-219.us-west-1.compute.amazonaws.com:8083 weight=5"
]
